### PR TITLE
Pr use ts for vite example

### PR DESCRIPTION
**Pull request by SquCode**

### CODE REVIEW

**Comment by brillout** [comment]
👍.

How about we make it ESM? Also, the tests are failing.

**Comment by SquCode** [comment]
I got stuck in that loop: https://stackoverflow.com/questions/62096269/cant-run-my-node-js-typescript-project-typeerror-err-unknown-file-extension
See also this: https://github.com/TypeStrong/ts-node/issues/935

So we would need to tsc it. But is that debuggingfriendly ? Maybe with sourcemaps. Or maybe you have a better idea.

**Comment by brillout** [comment]
Indeed I'm running into the same problem. There doesn't seem to be an obvious way to solve it but I've an idea.

**Comment by brillout** [comment]
Alright, this uses a pre-released patch of https://github.com/vitejs/vite/pull/9865. There won't be a need for a patch once the PR is merged.

**Pull request merged**
